var utsGanjil20 = [
    {
        title: 'Aljabar Linear',
        img: 'assets/diktat/uts-ganjil-2020.jpg',
        link: 'https://drive.google.com/file/d/1Yz6PW79474MKTbaahW0TBkDVB2bfHY4D/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Analisis Vektor dan Bilangan Kompleks',
        img: 'assets/diktat/uts-ganjil-2020.jpg',
        link: 'https://drive.google.com/file/d/19TzclpVrjyS5c0Ob5odk3L3G8w8B1cuE/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Analisis Vektor dan Bilangan Kompleks (Tekkom)',
        img: 'assets/diktat/uts-ganjil-2020.jpg',
        link: 'https://drive.google.com/file/d/1YUi7LwrIUARkZb_3YQ0xWPxS6OGF-nCi/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Dasar Sistem Digital',
        img: 'assets/diktat/uts-ganjil-2020.jpg',
        link: 'https://drive.google.com/file/d/1GvN-oih0ixyBiWqODa779cgLXT8NUNgP/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Fisika Listrik',
        img: 'assets/diktat/uts-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Kalkulus',
        img: 'assets/diktat/uts-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Matematika Teknik',
        img: 'assets/diktat/uts-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Probabilitas dan Proses Stokastik',
        img: 'assets/diktat/uts-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik (Tekkom)',
        img: 'assets/diktat/uts-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 2',
        img: 'assets/diktat/uts-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Kimia Dasar',
        img: 'assets/diktat/uts-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Dasar Rangkaian Elektronika',
        img: 'assets/diktat/uts-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]

var uasGanjil20 = [
    {
        title: 'Analisis Vektor dan Peubah Kompleks Elektro',
        img: 'assets/diktat/uas-ganjil-2020.jpg',
        link: 'https://drive.google.com/file/d/1Yz6PW79474MKTbaahW0TBkDVB2bfHY4D/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Analisis Vektor dan Peubah Kompleks Tekkom',
        img: 'assets/diktat/uas-ganjil-2020.jpg',
        link: 'https://drive.google.com/file/d/19TzclpVrjyS5c0Ob5odk3L3G8w8B1cuE/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Aljabar Linear',
        img: 'assets/diktat/uas-ganjil-2020.jpg',
        link: 'https://drive.google.com/file/d/1KJhqhwESDtE4MHbnyOTo2SOK2-XKBa_A/view',
        display: 'block',
    },
    {
        title: 'Kalkulus',
        img: 'assets/diktat/uas-ganjil-2020.jpg',
        link: 'https://drive.google.com/file/d/1GvN-oih0ixyBiWqODa779cgLXT8NUNgP/view?usp=sharing',
        display: 'block',
    },
    {
        title: 'Dasar Sistem Digital',
        img: 'assets/diktat/uas-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Fisika Listrik',
        img: 'assets/diktat/uas-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Probabilitas dan Proses Stokastik',
        img: 'assets/diktat/uas-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Matematika Teknik',
        img: 'assets/diktat/uas-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Kimia Dasar',
        img: 'assets/diktat/uas-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik 2',
        img: 'assets/diktat/uas-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Rangkaian Listrik Tekkom',
        img: 'assets/diktat/uas-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: 'Dasar Rangkaian Elektronika',
        img: 'assets/diktat/uas-ganjil-2020.jpg',
        link: '',
        display: 'block',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
    {
        title: '',
        img: '',
        link: '',
        display: 'none',
    },
]